### ISSUE TITLE
[Bug]:  User's level does not increase

### ISSUE THREAD

**Issue by lfcifuentes** [cjmellor/level-up#17]
### What happened?

When creating 3 levels as the documentation indicates, I carried out tests loading 50 points in my user repeatedly and although the points reached 100 to go to level 2, this never happened.
When implementing the `AUDIT_POINTS=true` option I could notice as if the attempt to level up was marked but my experience record remained at 1 even though my points were 250

### How to reproduce the bug

I created 3 levels as the documentation indicates:
```php
Level::add(
     ['level' => 1, 'next_level_experience' => null],
     ['level' => 2, 'next_level_experience' => 100],
     ['level' => 3, 'next_level_experience' => 250],
);
```
implement a route where I do this:
```php
$user = \App\Models\User::find(1);

$user->addPoints(50);
echo $user->getLevel();
echo $user->getPoints();
```
Run api calls to the route repeatedly

Environment Variables
```
LEVEL_CAP_ENABLED=true
LEVEL_CAP=3
LEVEL_CAP_POINTS_CONTINUE=true
AUDIT_POINTS=true
```

### Package Version

0.0.4

### PHP Version

8.2.8

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

### Notes

When I ran into this error, I did some tests on the package code and realized that I wasn't updating my experience level record but my points were.

While debugging, I changed in the `vendor/cjmellor/level-up/src/Concerns/GiveExperience.php` file the `line 160` in the `levelUp` method of and was able to solve my problem:

Before:
```php
$this->experience->status()->associate(model: $nextLevel);
````

After:
```php
$this->experience->status()->associate(model: $nextLevel)->save();
```

Could you tell me if I'm doing something wrong? 

I am using:
- Docker version 20.10.17, build 100c701
- PHP 8.2-fpm
- Postgres 13

**Comment by cjmellor** [comment]
Thanks for the report @lfcifuentes -- definitely a bug. Looking into it.
