### ISSUE TITLE
[Bug]: Event fired only once even when user has points for multiple levels

### ISSUE THREAD

**Issue by theveloperspl** [cjmellor/level-up#36]
### What happened?

Hello
I was messing around with your package and noticed very bad bug.
When points earned by user are enough to gain more than one level it gets increased only by one closest to level user currently has.
When next points are awarded next level is unlocked but it should be done in one run in my opinion as there may be along time before user earns next points and he will be stuck at lower level making functions like:
```
$user->nextLevelAt();
```
useless as they will display 0 as points requirements for next level are already met.
Is there any way to award multiple levels at one points increase operation?

### How to reproduce the bug

1. Setup default levels
```
Level::add(
    ['level' => 1, 'next_level_experience' => null],
    ['level' => 2, 'next_level_experience' => 100],
    ['level' => 3, 'next_level_experience' => 250],
);
```
2. Award user 300 points
```
$user->addPoints(300);
```
3. Only one UserLevelledUp event is fired with level 2
4. Award one more point:
```
$user->addPoints(1);
```
5. User level gets increased to level 3

### Package Version

v0.0.10

### PHP Version

8.1

### Laravel Version

10.2

### Which operating systems does with happen with?

Windows

**Comment by cjmellor** [comment]
Thanks for the report @theveloperspl 

I will look into a fix.

**Comment by theveloperspl** [comment]
I did check commit and what you changed was not the issue.
Problem is still with leveling only by one level even when points awarded should give more levels.
Lets say we have 5 levels
Level - required XP
1 - null
2 - 150
3 - 250
4 - 350
5 - 450
When user is awarded 300 points in one addPoints() method call he will still level up to only level 2 even though he should reach level 3.
Level 3 will be increased only when another addPoints() call is made.

**Comment by theveloperspl** [comment]
Issue as fixed for starting level but still persists on higher one.
For example user is on level 3 with 260 XP, then earns 180 additional XP in one addPoints() call which should level him to level 5 (with 440 total XP points) emitting events for both level 4 and 5 but this will not happen. 
He will be stuck at level 4( with met requirements for level 5 and broken nextLevelAt method showing 0) until another addPoints call is made.
I don't know how else I can explain to you what is the real issue I am talking about from the beginning.

**Comment by cjmellor** [comment]
PR is still in progress but thanks for the extra info.

**Comment by cjmellor** [comment]
I have these levels set up

```php
Level::add(
    ['level' => 1, 'next_level_experience' => null],
    ['level' => 2, 'next_level_experience' => 100],
    ['level' => 3, 'next_level_experience' => 250],
    ['level' => 4, 'next_level_experience' => 400],
    ['level' => 5, 'next_level_experience' => 600],
);
```

I give **User: 1** `260` points, and they're now at Level `3`.

I give the same user an extra `180` points, they're now at Level `4` with `440` XP.

Level 5 requires 600 points, so I added `170` (10 more than needed) to make `610` points, which puts them at Level `5`.

This is all correct and tests are passing, so I don't know where you might be going wrong, or whether I am still misunderstanding... though I don't think I am.

If you can give me step-by-step instructions on how you reached this newer issue, I can try to look into it further.

**Comment by theveloperspl** [comment]
Levels structure:
![image](https://github.com/cjmellor/level-up/assets/19894393/ad8d20d9-3e3f-4871-86af-01c6cc422f50)
I add points to user:
![image](https://github.com/cjmellor/level-up/assets/19894393/c10a6147-a01e-4e06-af80-31c3aa28b135)
And this is how DB results look like:
Experiences:
![image](https://github.com/cjmellor/level-up/assets/19894393/e807cb02-5182-4a16-b758-f0d95d51e7fb)
Experience audit:
![image](https://github.com/cjmellor/level-up/assets/19894393/76021593-60cd-4e7d-968c-8dd14c78a576)
Users table
![image](https://github.com/cjmellor/level-up/assets/19894393/0cf166fc-8f35-4f69-b638-724d72d45ea8)

Like I am saying, user level increases only by one instead of 2.
Maybe I am doing something wrong.

**Comment by cjmellor** [comment]
Do you have any `env` settings turned on/off in your `.env` ?

**Comment by theveloperspl** [comment]
Multipliers are disabled.
Level cap is enabled at 13.
Audit points is enabled.
ARCHIVE_STREAK_HISTORY_ENABLED is false.

**Comment by theveloperspl** [comment]
This is how event logs look like.
![image](https://github.com/cjmellor/level-up/assets/19894393/279beba8-26ae-46ea-adba-60ed4ce8aac8)
![image](https://github.com/cjmellor/level-up/assets/19894393/0849e8c7-8e0b-4029-b175-03c6c6d31849)

**Comment by theveloperspl** [comment]
All queries launched during addPoints() call
![image](https://github.com/cjmellor/level-up/assets/19894393/534bb3f9-64d2-4cfd-bbee-4b8a979f9c32)

**Comment by cjmellor** [comment]
I just cannot replicate it...

I even used the same points you've used, `500001` and it goes to Level `3`

<img width="610" alt="image" src="https://github.com/cjmellor/level-up/assets/1848476/f1102b35-3746-4949-814a-f9a83e4ddb75">

<img width="759" alt="image" src="https://github.com/cjmellor/level-up/assets/1848476/4cdc73ec-b03b-4b49-9b98-ec3a3db2f596">

Not sure what I can suggest further.

**Comment by theveloperspl** [comment]
In your example still event is fired only for level 3 and for level 2 there is not and it should be

**Comment by cjmellor** [comment]
Correct, only one event is fired. I don't see this as a "bug" per say so it's not something I'm gonna look into just yet, perhaps down the road or if it's demanded by more users. 

I am open to a PR for it though.

**Comment by theveloperspl** [comment]
@cjmellor 
I just tried on fresh Laravel installation with only your package installed and there is the same problem.
First I call method:
$user->addPoints(0); to create experiences record.
Then using default levels from documentation I call method:
$user->addPoints(250);
and leveling is still locked to level 2 instead of 3.

![image](https://github.com/cjmellor/level-up/assets/19894393/bf5d8814-7d9e-4832-bb30-cae37aeca576)
![image](https://github.com/cjmellor/level-up/assets/19894393/694c58c5-6ec3-44a1-a81f-7abc623297d9)
![image](https://github.com/cjmellor/level-up/assets/19894393/3ed07688-4c3b-4e9c-a56a-db0cf9b06670)
![image](https://github.com/cjmellor/level-up/assets/19894393/e4c3885b-2dff-49e7-95b5-05470871798c)

**Comment by cjmellor** [comment]
What Database do you use?

**Comment by theveloperspl** [comment]
MySQL on Windows

**Comment by theveloperspl** [comment]
When I run code like this it works like expected:
![image](https://github.com/cjmellor/level-up/assets/19894393/e9547ff3-a45f-46ee-b2af-29c6966547d6)
![image](https://github.com/cjmellor/level-up/assets/19894393/c0810db0-8a6f-40b0-8b76-f4ca8839f862)
But that 0 points must be added with all related records for correct level() relationship work and nextLevelAt() method in my application.

**Comment by cjmellor** [comment]
Okay, finally, I get you... It's bugged when you set the points to zero, to begin with.

**Comment by theveloperspl** [comment]
I have managed to modify package to handle all issues I had properly.
It now works with starting 0 balance, fires leveled up event on every level user gains.
Instead of throwing exception when given XP is too high it just replaces amount with highest possible.
I will try to optimize whole package code especially multiple, unnecessary DB calls and n+1 queries and probably will make PR next week.

**Comment by cjmellor** [comment]
Sounds good! Thanks for contributing 😄
