### ISSUE TITLE
first migration [Bug]: 

### ISSUE THREAD

**Issue by Temian1** [cjmellor/level-up#43]
### What happened?

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value
for 'ended_at' (Connection: mysql, SQL: create table `streak_histories` (`id` bi
gint unsigned not null auto_increment primary key, `user_id` bigint unsigned not
 null, `activity_id` bigint unsigned not null, `count` int not null default '1',
 `started_at` timestamp not null, `ended_at` timestamp not null, `created_at` ti
mestamp null, `updated_at` timestamp null) default character set utf8mb4 collate
 'utf8mb4_unicode_ci')

### How to reproduce the bug

i try to do fresh migrate

### Package Version

2

### PHP Version

8

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by cjmellor** [comment]
I need more information on the bug than what you have provided

**Comment by Temian1** [comment]
When I installed the package following the steps , I tried to migrate and I got that error

**Comment by cjmellor** [comment]
Can you be more specific? Write step-by-step the steps you take until you hit the error
